debug: false

title: Le Blog de Marcos Ickx
name: Le Blog de Marcos Ickx
url: https://blog.marcosx.net
author: Marcos Ickx
markdown: kramdown

# theme: jekyll-theme-minimal
#format date exemple 09/01/2023
date_format: "%d/%m/%Y"
locale: fr-BE
timezone: Europe/Brussels

# Site Author
author:
  name: Marcos Ickx
  twitterId: MarcosIckx
  aboutUrl: /apropos/MarcosIckx
  url: /apropos/MarcosIckx

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
permalink: /:year/:month/:day/:title.html

plugins:
  - jekyll-mentions
  - jekyll-relative-links
  - jekyll-redirect-from

# things like @MarcosIckx will be transformed into link to twitter account
jekyll-mentions:
  base_url: https://twitter.com

relative_links:
  enabled:     true
  collections: true

# exclude creation of a json file
redirect_from:
  json: false
  
#plugins:
#   - jekyll-paginate
#
#paginate: 10

include: ['_pages']

collections:
  archives:
    output: true
  authors:
    output: true
    permalink: /apropos/:title/
    
defaults:
  -
    scope:
      path: ""
      type: "archives"
    values:
      layout: "archives"
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
    
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Marcos Ickx"
  - 
    scope:
      path: "/2007/"
      type: "posts"
    values:
      layout: "post"
      author: "Marcos Ickx"
      permalink: /:year/:month/:day/:title/
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      author: "Marcos Ickx"
