title: Le Blog de Marcos Ickx
name: Le Blog de Marcos Ickx
markdown: kramdown
theme: jekyll-theme-minimal

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
permalink: /:year/:month/:day/:title.html

plugins:
   - jekyll-paginate

paginate: 10

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Marcos Ickx"
