debug: false

title: Le Blog de Marcos Ickx
name: Le Blog de Marcos Ickx
url: https://blog.marcosx.net
author: Marcos Ickx
markdown: kramdown

# theme: jekyll-theme-minimal
#format date exemple 09/01/2023
date_format: "%d/%m/%Y"
locale: fr-BE
timezone: Europe/Brussels

# Site Author
author:
  name: Marcos Ickx
  twitterId: MarcosIckx
  aboutUrl: /apropos/
  url: /apropos/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
permalink: /:year/:month/:day/:title.html

plugins:
   - jekyll-paginate

paginate: 10

include: ['_pages']

collections:
  archives:
    output: true
  authors:
    output: true
    permalink: /apropos/:title/
    
defaults:
  -
    scope:
      path: ""
      type: "archives"
    values:
      layout: "archives"
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
    
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Marcos Ickx"
      
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      author: "Marcos Ickx"
