name: Le Blog de Marcos Ickx
markdown: kramdown
theme: jekyll-theme-minimal

permalink: /:year/:month/:day/:title.html

gems:
   - jekyll-paginate

paginate: 10

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      author: "Marcos Ickx"
